<script>
	import _ from "lodash";
	export let book;
</script>

<form class="w-full max-w-lg" action="">
	<div class="card mb-6">

		<div class="card-header flex justify-between">
			<span class="card-title">eBook</span>
			<div class="mb-4">
				{#if book.config.ebook.enabled}
					<i class="fas fa-toggle-on" />
				{:else}
					<i class="fas fa-toggle-off" />
				{/if}
			</div>
		</div>

		{#if book.config.ebook.enabled}
			<div class="card-body">
				<div class="mb-3">
					<label class="block text-gray-700 text-md font-bold mb-2">
						Theme
					</label>
					<span>{book.config.ebook.theme}</span>
				</div>
			</div>

			<div class="italic">
				The eBook will be assembled in EPUB3 non-DRM format.
			</div>
		{:else}
			<div class="italic">
				eBook support is disabled in your configuration.
			</div>
		{/if}

	</div>

	<div class="card mb-6">

		<div class="card-header flex justify-between">
			<span class="card-title">Website</span>
			<div class="mb-4">
				{#if book.config.pwa.enabled}
					<i class="fas fa-toggle-on" />
				{:else}
					<i class="fas fa-toggle-off" />
				{/if}
			</div>
		</div>

		{#if book.config.pwa.enabled}
			<div class="card-body">
				<div class="mb-3">
					<label class="block text-gray-700 text-md font-bold mb-2">
						Web Monetization
					</label>
					{#if book.config.webmonetization.enabled}
						<span>Enabled</span>
					{:else}
						<span>Disabled</span>
					{/if}
				</div>

				<div class="mb-3">
					<label class="block text-gray-700 text-md font-bold mb-2">
						Web Monetization Endpoint
					</label>
					<span>{book.config.webmonetization.endpoint}</span>
				</div>
			</div>

			<div class="italic">
				The website generated by this tool is a static website that can be
				deployed to any webserver.
			</div>
		{:else}
			<div class="italic">
				Website support is disabled in your configuration.
			</div>
		{/if}
	</div>
</form>
