<script>
  import _ from "lodash";
  export let book;
</script>

<form class="form mt-2" action="">
  <div class="card mb-3">
    <div class="card-header d-flex justify-content-between">
      <span>eBook</span>
      <div class="form-check form-switch">
        <input
          class="form-check-input"
          type="checkbox"
          bind:checked={book.config.ebook.enabled} />
        <label class="form-check-label" for="flexSwitchCheckChecked">
          Create eBook.
        </label>
      </div>
    </div>
    <div class="card-body">
      <div class="mb-3">
        <label class="form-label">Theme</label>
        <select class="form-select" bind:value={book.config.ebook.theme}>
          <option>Choose a theme</option>
          <option value="technical">Technical</option>
          <option value="fiction">Fiction</option>
        </select>
      </div>
    </div>
    <div class="card-footer text-muted">
    The eBook is created in EPUB3 non-DRM format.
    </div>
  </div>
  <div class="card mb-3">
    <div class="card-header d-flex justify-content-between">
      <span>Website</span>
      <div class="form-check form-switch">
        <input
          class="form-check-input"
          type="checkbox"
          bind:checked={book.config.website.enabled} />
        <label class="form-check-label" for="flexSwitchCheckChecked">
          Create website.
        </label>
      </div>
    </div>
    <div class="card-body">
      <div class="mb-3">
        <div class="form-check form-switch">
          <input
            type="checkbox"
            class="form-check-input"
            bind:checked={book.config.webmonetization.enabled} />
          <label class="form-check-label">Enable Web Monetatization.</label>
        </div>
      </div>
      <div class="mb-3">
        <label class="form-label">Webmonetization Endpoint</label>
        <input
          class="form-control"
          type="text"
          disabled={!book.config.webmonetization.enabled}
          bind:value={book.config.webmonetization.endpoint} />
      </div>
    </div>
    <div class="card-footer text-muted">
      The website generated by this tool is a static website that can be
      deployed to any webserver.
    </div>
  </div>
</form>
