<script>
	import _ from "lodash";
	export let book;
</script>

<form class="w-full max-w-lg" action="">
	<div class="card mb-6">

		<div class="card-header flex justify-between">
			<span class="card-title">eBook</span>
			<div class="mb-4">
				<input type="checkbox" bind:checked={book.config.ebook.enabled} />
				<label
					class="text-gray-700 text-sm font-bold mb-2"
					for="flexSwitchCheckChecked">
					Create eBook.
				</label>
			</div>
		</div>

		<div class="card-body">
			<div class="mb-3">
				<label class="block  text-gray-700 text-md font-bold mb-2">Theme</label>
				<div class="inline-block relative w-64">
					<select
						class="block appearance-none w-full bg-white border border-gray-400
						hover:border-gray-500 px-4 py-2 pr-8 rounded shadow leading-tight
						focus:outline-none focus:shadow-outline"
						bind:value={book.config.ebook.theme}>
						<option>Choose a theme</option>
						<option value="technical">Technical</option>
						<option value="fiction">Fiction</option>
					</select>
					<div
						class="pointer-events-none absolute inset-y-0 right-0 flex
						items-center px-2 text-gray-700">
						<svg
							class="fill-current h-4 w-4"
							xmlns="http://www.w3.org/2000/svg"
							viewBox="0 0 20 20">
							<path
								d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757
								6.586 4.343 8z" />
						</svg>
					</div>
				</div>
			</div>
		</div>

		<div class="italic">The eBook is created in EPUB3 non-DRM format.</div>

	</div>

	<div class="card mb-6">

		<div class="card-header flex justify-between">
			<span class="card-title">Website</span>
			<div class="mb-4">
				<input
					class=""
					type="checkbox"
					bind:checked={book.config.pwa.enabled} />
				<label
					class="text-gray-700 text-sm font-bold mb-2"
					for="flexSwitchCheckChecked">
					Create website.
				</label>
			</div>
		</div>

		<div class="card-body">
			<div class="mb-3">
				<div class="form-check form-switch">
					<input
						type="checkbox"
						class="form-check-input"
						bind:checked={book.config.webmonetization.enabled} />
					<label class="form-check-label">Enable Web Monetatization.</label>
				</div>
			</div>

			<div class="mb-3">
				<label class="block  text-gray-700 text-md font-bold mb-2">Webmonetization Endpoint</label>
				<input
					class="block appearance-none w-full bg-white border border-gray-400
						hover:border-gray-500 px-4 py-2 pr-8 rounded shadow leading-tight
						focus:outline-none focus:shadow-outline"
					type="text"
					disabled={!book.config.webmonetization.enabled}
					bind:value={book.config.webmonetization.endpoint} />
			</div>

		</div>

		<div class="italic">
			The website generated by this tool is a static website that can be
			deployed to any webserver.
		</div>

	</div>
</form>
