[metadata]
title = "Book Configuration Specification"
subtitle = "A comprehensive guide to the book configuration file"
date = 2021-10-06T12:00:00Z
identifier = "https://litte.webby.press/books/book-configuration-specification"
cover = "images/cover.png"
license = "<a href='https://creativecommons.org/licenses/by-nc/4.0/deed.en_GB'><img src='book/images/license.svg'></a>"

[author]
name = "André Alves Garzia"
bio = """
Andre is writer and developer. In the recent years he published books about programming and managed a Web Literacy program in vulnerable neighborhoods of Rio. He is a firm believer in empowerment through technological experimentation. He lives in London with his wife, cats and more IoT boards than he can ever put into use.
"""
photo = "images/author.png"

[[links]]
label = "Twitter"
url = "https://twitter.com/soapdog"

[[links]]
label = "Blog"
url = "https://andregarzia.com"

[[cta]]
url = "https://example.com"
label = "Download example"

[publisher]
name = "Little Webby Press"

[site]
landing = false

[webmonetization]
endpoint = "$ilp.uphold.com/zdPRwAnyEkmM"


[book]
chapters = [
  "introduction.md",
  "toml.md",
  "metadata.md",
  "author.md",
  "book.md",
  "toc.md",
  "publisher.md",
  "site.md",
  "webmonetization.md",
  "cta.md",
  "links.md",
  "yaml.md",
  "json.md",
  "conclusion.md"
]
